# -*- coding: utf-8 -*-
"""Riya_T107(P2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QiEhEFgmk7yr2cgLtlHDERQE-eGQrY5Y
"""

# Riya Rane
#T107 TYCS

dict_gn = {
    'Ghatkopar': {'Vikhroli': 5, 'Kurla': 6},
    'Vikhroli': {'Ghatkopar': 5, 'Powai': 4},
    'Powai': {'Vikhroli': 4, 'Sion': 8},
    'Kurla': {'Ghatkopar': 6, 'Sion': 5},
    'Sion': {'Kurla': 5, 'Powai': 8, 'Byculla': 9},
    'Byculla': {'Sion': 9, 'RaniBaug': 2},
    'RaniBaug': {'Byculla': 2}
}


start = "Ghatkopar"
goal = "RaniBaug"

result = ""


def DLS(city, visitedstack, startlimit, endlimit):
    global result

    result = result + city + " "
    visitedstack.append(city)


    if city == goal:
        return True


    if startlimit == endlimit:
        visitedstack.pop()
        return False


    for eachcity in dict_gn[city]:
        if eachcity not in visitedstack:
            found = DLS(eachcity, visitedstack, startlimit + 1, endlimit)
            if found:
                return True

    visitedstack.pop()
    return False



def IDDFS(city, endlimit):
    global result

    for limit in range(endlimit + 1):
        print("Searching at Limit:", limit)

        visitedstack = []
        result = ""

        found = DLS(city, visitedstack, 0, limit)

        if found:
            print("Found!")
            return

        print("Not Found!")
        print("---------------------")



def main():
    global result

    IDDFS(start, 10)

    print("\nIDDFS Traversal from", start, "to", goal, "is:")
    print(result)



main()